### ISSUE TITLE
Use LocalStorage to save notes unlocked & settings

### ISSUE THREAD

**Issue by MayMoonsley** [MayMoonsley/inheritance#31]

**Comment by kanwren** [comment]
#38 has been opened tentatively implementing LocalStorage, and implementations have been filled in for saving and restoring note data. We don't have any settings yet, so the settings-storage-related methods have only been stubbed out.

**Comment by kanwren** [comment]
#40 implements saving settings. To add new settings, add the appropriate fields/getters/setters to `Settings` and add a corresponding field in `SettingsOptions` so we know what the structure should look like when it's parsed.
