### ISSUE TITLE
create content for lore notes

### ISSUE THREAD

**Issue by grarer** [MayMoonsley/inheritance#34]
the system for showing lore notes is in place but it's still placeholder content; we should create some actual notes

**Comment by MayMoonsley** [comment]
Lore Note Content Needed:

- [ ] Tutorial Note

Character notes:

- [x] Granddaughter
- [x] Clone
- [ ] Catburglar
- [x] Reject 
- [x] Shell

Ideally, any bosses should have lore notes as well, but that's less important. Feel free to add additional notes as well (though I reserve the right to exercise my veto power.)
